### ISSUE TITLE
Python3 version?

### ISSUE THREAD

**Issue by psychemedia** [ucsd-ccbb/visJS2jupyter#1]
Are there many python 2 dependencies in the code that would get in the way of making a python3 version?

Trying to install under py3 I get an immediate break on a `print ` statement which got me wondering if there was much more than that in the way of moving to py3?

**Comment by brinrosenthal** [comment]
Hello, yes the package was written for python2.  We are currently working on making it compatible with both 2 and 3, as there shouldn't be too many version-specific elements.

**Comment by smartinsightsfromdata** [comment]
@brinrosenthal I understand that this is open source (and we are grateful for the time you have already put into this!).

But it would be helpful to have an indication on the timeframe, e.g. a week, a month or a quarter :)

Again thanks in advance.

**Comment by brinrosenthal** [comment]
Hi @smartinsightsfromdata - we're working on they python3 compatibility now, and I expect we will have it done within a couple weeks, barring unforeseen problems.  Hope that helps!

**Comment by julialen** [comment]
@psychemedia and @smartinsightsfromdata: Python 3 compatibility has just been added

**Comment by smartinsightsfromdata** [comment]
great stuff! greatly appreciated.
