### ISSUE TITLE
Mulitple plot in the same notebook are not rendering

### ISSUE THREAD

**Issue by davidvarenne** [ucsd-ccbb/visJS2jupyter#13]
Hello,
I want to thank you for this beautiful library, very helpful! 
I was playing with it and I tried to plot, in the same jupyter notebook, multiple Graph example. When I try to plot the second one is not rendering anything but an empty figure.

To replicate the problem is sufficient to execute the same simple plot in two different cells!

Does this sound familiar to anyone?
Hope to be clear,

Thank you

**Comment by davidvarenne** [comment]
ok, solve it with the time_stamp parameter!

**Comment by brinrosenthal** [comment]
hi david, glad the package is helpful to you!

setting the **graph_id** argument to a unique integer for every graph you have within one notebook will also solve this problem.  **time_stamp** will still work, but is a deprecated argument
