### ISSUE TITLE
TypeError on import

### ISSUE THREAD

**Issue by jarmarshall** [ucsd-ccbb/visJS2jupyter#17]
I am using python 3.6.4 and Jupyter 5.5.0... I cannot even import the package, which throws
`TypeError: Javascript expects text, not b'/**\r\n * vis.js\r\n * https://github.com/almende/vis\r\n *`[....] (there is a *lot* of text in the [....])

**Comment by jonrichens** [comment]
I get the same error when trying to import

**Comment by m1webste** [comment]
Another user had this issue and found a fix. This fix has been reflected on git, but not yet on pipy. We'll update that very soon.

**Comment by jarmarshall** [comment]
Ah yes, sorry - just found issue #16

**Comment by m1webste** [comment]
I've updated the pypi. Could you try importing it again and letting me know if you still have that problem?

**Comment by jarmarshall** [comment]
Yes, this now imports fine, thanks - I look forward to trying out the package!
