### ISSUE TITLE
ImportError: No module named 'scipy_heatKernel'

### ISSUE THREAD

**Issue by schlegelp** [ucsd-ccbb/visJS2jupyter#20]
When importing `from visJS2jupyter import visualizations` in Python3, I get the above error. 

Culprit is this line - which should work for all I know:

https://github.com/ucsd-ccbb/visJS2jupyter/blob/497dbc34a15eb74c7ef4909e9398b6b53885fd9f/visJS2jupyter/visualizations.py#L22

Nevertheless, changing it to
```python
from visJS2jupyter import scipy_heatKernel
```
fixed it for me.

**Comment by brinrosenthal** [comment]
thanks for pointing out this problem! Pypi version 0.1.17 of the package was proving problematic for a number of people, so we rolled back to pypi version 0.1.16, which should also resolve this import problem

**Comment by psychemedia** [comment]
I just tried running the repo `master` branch in MyBinder and, after running `pip install ` commands where required (`pandas`, `networkx`, `mygene`) got the same error trying to run `validate_heat_prop_autism_2.ipynb`.

By the by, Python packages can be automatically installed in a MyBinder / Binderhub build by adding a `binder/requirements.txt` file to the repo. The `binder` directory can also include a range of [other config files](https://mybinder.readthedocs.io/en/latest/config_files.html).
