### ISSUE TITLE
No setup.py

### ISSUE THREAD

**Issue by bjodah** [ucsd-ccbb/visJS2jupyter#24]
First of all, thank you for making this package available. It looks really promising (and I'm eager to try it out).

In commit:
https://github.com/ucsd-ccbb/visJS2jupyter/commit/7e1bd04a480e69126561ea761e22f3d46f5eafbd

setup.py was removed. Was that intentional? (I cannot pip install https://github.com/ucsd-ccbb/visJS2jupyter/archive/master.tar.gz) because of missing setup.py

(the reason I'm trying this is because I experience gh-17 when using the version on PyPI).

**Comment by brinrosenthal** [comment]
no not intentional- thanks for replacing it!
