### ISSUE TITLE
Examples not working anymore.

### ISSUE THREAD

**Issue by jmbertoncelli** [ucsd-ccbb/visJS2jupyter#4]
# add a node attributes to color-code by
cc = nx.clustering(G)
degree = G.degree()
bc = nx.betweenness_centrality(G)
nx.set_node_attributes(G,'clustering_coefficient',cc)
nx.set_node_attributes(G,'degree',degree)
nx.set_node_attributes(G,'betweenness_centrality',bc)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-85ac86e0c1f3> in <module>()
      3 degree = G.degree()
      4 bc = nx.betweenness_centrality(G)
----> 5 nx.set_node_attributes(G,'clustering_coefficient',cc)
      6 nx.set_node_attributes(G,'degree',degree)
      7 nx.set_node_attributes(G,'betweenness_centrality',bc)

/root/miniconda2/envs/snake27.10/lib/python2.7/site-packages/networkx/classes/function.pyc in set_node_attributes(G, values, name)
    646         except AttributeError:  # `values` is a constant
    647             for n in G:
--> 648                 G.nodes[n][name] = values
    649     else:  # `values` must be dict of dict
    650         for n, d in values.items():

TypeError: unhashable type: 'dict'

**Comment by jmbertoncelli** [comment]
Does not work when using networkX 2.0 but works with networkX 1.11.  Do you plan to upgrade your code to be compatible with nx 2.x?

**Comment by jmbertoncelli** [comment]
Any news about support for nx 2.x?

thanks

**Comment by brinrosenthal** [comment]
thank you for bringing this issue to our attention- we are working on upgrading the tool to be compatible with nx 2.0.  We expect to have the new version ready within the next week.

**Comment by jmbertoncelli** [comment]
Thanks a lot for this excellent library!  Would you keep me posted to when the update should be available on pypi?

Thanks a lot

Jm

Sent from my iPhone

On Oct 24, 2017, at 11:40 AM, brinrosenthal <notifications@github.com<mailto:notifications@github.com>> wrote:


thank you for bringing this issue to our attention- we are working on upgrading the tool to be compatible with nx 2.0. We expect to have the new version ready within the next week.

**Comment by brinrosenthal** [comment]
Hi JM,

We've just updated to version 0.1.8, which is now compatible with nx2.0.  We've also updated the notebooks so they are compatible as well (by casting nodeview/edgeview  objects to lists).  Hope you can use the tool now!

-SBR

**Comment by jmbertoncelli** [comment]
Thank you a bunch!
JM


Sent from my iPad

On Nov 8, 2017, at 3:35 PM, brinrosenthal <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #4<https://github.com/ucsd-ccbb/visJS2jupyter/issues/4>.
