### ISSUE TITLE
Cytoscape Export Function 

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/visJS2jupyter#8]
I was able to successfully export a json object with export_network =True according to the documentation, but when I try to load the json document into Cytoscape v3.6.0 I get this error. Thanks!
<img width="547" alt="cytoscape_task_and_session__new_session" src="https://user-images.githubusercontent.com/5123063/34064557-bc89bc56-e1ae-11e7-8d88-228896bfa8b7.png">

**Comment by brinrosenthal** [comment]
this issue should be resolved with upgrading to the new version (0.1.9)
